---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-couchpotato-conf
  labels:
    name: nfs-conf # name can be anything
spec:
  storageClassName: manual # same storage class as pvc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.27 # ip addres of nfs server
    path: "/media/nfs/" # path to directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-couchpotato-config
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-couchpotato-downloads
  labels:
    name: nfs-conf # name can be anything
spec:
  storageClassName: manual # same storage class as pvc
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.27 # ip addres of nfs server
    path: "/media/nfs/" # path to directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-couchpotato-downloads
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 250Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-couchpotato-tv
  labels:
    name: nfs-tv # name can be anything
spec:
  storageClassName: manual # same storage class as pvc
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.27 # ip addres of nfs server
    path: "/media/nfs/" # path to directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-couchpotato-tv
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchpotato-deployment
  labels:
    app: couchpotato
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchpotato
  template:
    metadata:
      labels:
        app: couchpotato
    spec:
      containers:
      - name: couchpotato
        image: linuxserver/couchpotato
        ports:
        - containerPort: 6789
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - mountPath: /config
          name: couchpotato-config
          readOnly: false
          subPath: usenet/couchpotato/config
        - mountPath: /downloads
          name: couchpotato-downloads
          readOnly: false
          subPath: usenet/sabnzbd/downloads
        - mountPath: /tv
          name: couchpotato-tv
          readOnly: false
          subPath: usenet/sabnzbd/tv
      volumes:
      - name: couchpotato-config
        persistentVolumeClaim:
          claimName: nfs-pvc-couchpotato-config
      - name: couchpotato-downloads
        persistentVolumeClaim:  
          claimName: nfs-pvc-couchpotato-downloads
      - name: couchpotato-tv
        persistentVolumeClaim:  
          claimName: nfs-pvc-couchpotato-tv
---
kind: Service
apiVersion: v1
metadata:
  name: couchpotato-service
spec:
  selector:
    app: couchpotato
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
  type: LoadBalancer