---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-flextv-conf
  labels:
    name: nfs-conf # name can be anything
spec:
  storageClassName: manual # same storage class as pvc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.27 # ip addres of nfs server
    path: "/media/nfs/" # path to directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-flextv-config
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flextv-deployment
  labels:
    app: flextv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flextv
  template:
    metadata:
      labels:
        app: flextv
    spec:
      containers:
      - name: flextv
        image: boyroywax/flextv:latest
        ports:
        - containerPort: 6789
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - mountPath: /config
          name: flextv-config
          readOnly: false
          subPath: usenet/flextv/config
      volumes:
      - name: flextv-config
        persistentVolumeClaim:
          claimName: nfs-pvc-flextv-config
---
kind: Service
apiVersion: v1
metadata:
  name: flextv-service
spec:
  selector:
    app: flextv
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer