---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-sickgear-conf
  labels:
    name: nfs-conf # name can be anything
spec:
  storageClassName: manual # same storage class as pvc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.27 # ip addres of nfs server
    path: "/media/nfs/" # path to directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-sickgear-config
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-sickgear-downloads
  labels:
    name: nfs-conf # name can be anything
spec:
  storageClassName: manual # same storage class as pvc
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.27 # ip addres of nfs server
    path: "/media/nfs/" # path to directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-sickgear-downloads
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 250Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-sickgear-tv
  labels:
    name: nfs-tv # name can be anything
spec:
  storageClassName: manual # same storage class as pvc
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.27 # ip addres of nfs server
    path: "/media/nfs/" # path to directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-sickgear-tv
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sickgear-deployment
  labels:
    app: sickgear
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sickgear
  template:
    metadata:
      labels:
        app: sickgear
    spec:
      containers:
      - name: sickgear
        image: linuxserver/sickgear
        ports:
        - containerPort: 6789
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - mountPath: /config
          name: sickgear-config
          readOnly: false
          subPath: usenet/sickgear/config
        - mountPath: /downloads
          name: sickgear-downloads
          readOnly: false
          subPath: usenet/sabnzbd/downloads
        - mountPath: /tv
          name: sickgear-tv
          readOnly: false
          subPath: usenet/sabnzbd/tv
      volumes:
      - name: sickgear-config
        persistentVolumeClaim:
          claimName: nfs-pvc-sickgear-config
      - name: sickgear-downloads
        persistentVolumeClaim:  
          claimName: nfs-pvc-sickgear-downloads
      - name: sickgear-tv
        persistentVolumeClaim:  
          claimName: nfs-pvc-sickgear-tv
---
kind: Service
apiVersion: v1
metadata:
  name: sickgear-service
spec:
  selector:
    app: sickgear
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer