---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-nextcloud-conf
  labels:
    name: nfs-conf # name can be anything
spec:
  storageClassName: manual # same storage class as pvc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.27 # ip addres of nfs server
    path: "/media/nfs/" # path to directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-nextcloud-config
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-nextcloud-data
  labels:
    name: nfs-data # name can be anything
spec:
  storageClassName: manual # same storage class as pvc
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.27 # ip addres of nfs server
    path: "/media/nfs/" # path to directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-nextcloud-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: linuxserver/nextcloud
        ports:
        - containerPort: 6789
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - mountPath: /config
          name: nextcloud-config
          readOnly: false
          subPath: server/nextcloud/config
        - mountPath: /data
          name: nextcloud-data
          readOnly: false
          subPath: server/nextcloud/data
      volumes:
      - name: nextcloud-config
        persistentVolumeClaim:
          claimName: nfs-pvc-nextcloud-config
      - name: nextcloud-data
        persistentVolumeClaim:  
          claimName: nfs-pvc-nextcloud-data
---
kind: Service
apiVersion: v1
metadata:
  name: nextcloud-service
spec:
  selector:
    app: nextcloud
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer