apiVersion: skaffold/v1alpha2
kind: Config
# build:
#   artifacts:
#   - imageName: boyroywax/flextv
#     workspace: ./flextv/FlexTV-docker
deploy:
  kubectl:
    manifests:
      - ./nextcloud-deployment.yaml